# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G


# Base properties
    # minecraft version
    minecraft_version=1.21.1
    # Match the NeoForge build used by All the Mods 10 - 8.0 Migrated.
    neoforge_version=21.1.248
    neoforge_version_range=[21.1.240,)
    loader_version=4
    mapping_channel=parchment
    mapping_version=2024.11.17

# Mod Properties
    mod_version=0.4.0
    maven_group=com.raishxn.gtna
    archives_base_name=gtna
    mod_id=gtna
    mod_name=GregTech: Nexus Addon
    mod_url= https://github.com/Raishxn/GregTech-Nexus-Addon
    mod_author=Raishxn
    mod_license=LGPLv3.0

# Dependencies
    gtceu_version=8.0.1-atm10.5
    ae2_version=19.2.17
    extendedae_version=2.2.35
    advancedae_version=1.6.12
    guideme_version=21.1.17
    ldlib2_version=2.2.36
    ldlib_compat_version=1.0.41
